/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import ui.image.FileTransfer;
import ui.swing.imageLink.ImageLink;
import ui.swing.utils.ColorController;
import ui.swing.webLaf.WeblafUtils;

/**
 *
 * @author lite
 */
public class ImageLinkPanel extends javax.swing.JPanel {
    
    ImageLink imageLink;
    
    private boolean selected = false;
    
    /**
     * Creates new form ImageLinkPanel
     * @param imageLink
     */
    public ImageLinkPanel(ImageLink imageLink) {
        initComponents();
        
        this.imageLink = imageLink;
        this.imageLink.getImageLoader().setIlp(this);
        
        
        WeblafUtils.configuraWebLaf(jCheckBox1);
        imagePanel.setIcon(new ImageIcon(this.imageLink.getImageLoader().getImageThumb()));
        imagePanel.setText("");
        size.setText("");
        nameLabel.setText(this.imageLink.getNome());
        setBackground(ColorController.COR_DESTAQUE);
        jPanel6.setBackground(ColorController.COR_PRINCIPAL);
        nameLabel.setForeground(ColorController.COR_LETRA);
        size.setForeground(ColorController.COR_LETRA);
        WeblafUtils.configurarBotao(downloadButton, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, 10);
        WeblafUtils.configurarBotao(downloadButton1, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, 10);
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        if(selected){
            setBackground(ColorController.FUNDO_ESCURO);
        }else{
            setBackground(ColorController.COR_DESTAQUE);
        }
        invalidate();
        repaint();
    }
    
    public void update(){
        imagePanel.setIcon(new ImageIcon(this.imageLink.getImageLoader().getImageThumb()));
        nameLabel.setText(this.imageLink.getNome());
        size.setText("("+imageLink.getImageLoader().getImageWidth()+"x"+imageLink.getImageLoader().getImageHeight()+")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        size = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        nameLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        downloadButton = new com.alee.laf.button.WebButton();
        downloadButton1 = new com.alee.laf.button.WebButton();
        imagePanel = new javax.swing.JLabel();

        jPanel2.setMinimumSize(new java.awt.Dimension(10, 8));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(10, 8));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel6.setPreferredSize(new java.awt.Dimension(400, 1));
        jPanel2.add(jPanel6);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        size.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        size.setText("size");
        jPanel3.add(size, java.awt.BorderLayout.SOUTH);
        jPanel3.add(jCheckBox1, java.awt.BorderLayout.EAST);

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("name");
        jPanel3.add(nameLabel, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        downloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/preview.png"))); // NOI18N
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });
        jPanel4.add(downloadButton);

        downloadButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/download.png"))); // NOI18N
        downloadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(downloadButton1);

        jPanel5.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        imagePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePanel.setText("image");
        imagePanel.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(imagePanel, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        Application.getInstance().previewImage(imageLink.getImageLoader().getImage());
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        setSelected(true);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        setSelected(false);
    }//GEN-LAST:event_jPanel1MouseExited

    private void downloadButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButton1ActionPerformed
        String url = imageLink.getUrl();
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("/home/me/Documents"));
        chooser.setSelectedFile(new File(imageLink.getNome()));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                FileTransfer.saveFile(chooser.getSelectedFile().toString(), url.substring(url.length()-3),(BufferedImage) imageLink.getImageLoader().getImage());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_downloadButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton downloadButton;
    private com.alee.laf.button.WebButton downloadButton1;
    private javax.swing.JLabel imagePanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel size;
    // End of variables declaration//GEN-END:variables
}
